services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: products_user
      POSTGRES_PASSWORD: products_password
      POSTGRES_DB: products
    ports:
      - "5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
