spring:
  application:
    name: products

  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: products_user
    password: products_password
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.mango: DEBUG
